FROM node:24-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS build
COPY . .
RUN npm run build

FROM node:24-slim
WORKDIR /app
COPY --from=build /app ./
ENV NODE_ENV=production
CMD ["npm", "run", "start"]
