FROM node:24-slim
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
ENV NODE_ENV=production
COPY lib ./lib
COPY scripts ./scripts
COPY tsconfig.json ./
CMD ["npx", "tsx", "scripts/worker.ts", "--daemon"]
